[project]
name = "docker-mlflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.36.0",
    "certifi>=2024.7.4", # vuln
    "cryptography>=44.0.1", # vuln
    "filelock>=3.20.1", # vuln
    "fonttools>=4.60.2", # vuln
    "mlflow==3.8.1",
    "psycopg2-binary==2.9.11",
    "urllib3>=2.6.0", # vuln
    "werkzeug>=3.1.4", # vuln
]

[dependency-groups]
dev = [
    "litellm[proxy]==1.80.17",  # this version works
    "openai>=2.7.2",
    "scikit-learn==1.8.0",
]
