[project]
name = "docker-mlflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.36.0",
    "flask==3.1.1", # vuln
    "h11==0.16.0", # vuln
    "jinja2==3.1.6", # vuln
    "mlflow==3.8.1",
    "protobuf==5.29.5", # vuln
    "psycopg2-binary==2.9.11",
    "requests==2.32.4", # vuln
    "starlette>=0.49.1", # vuln
    "urllib3==2.5.0", # vuln
]

[dependency-groups]
dev = [
    "litellm[proxy]==1.80.11",  # this version works
    "openai>=2.7.2",
    "scikit-learn==1.8.0",
]
