[project]
name = "docker-mlflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3==1.40.10",
    "mlflow==3.3.2",
    "psycopg2-binary==2.9.11",
]

[tool.uv]
dev-dependencies = [
    "scikit-learn==1.7.2",
]
