[project]
name = "docker-mlflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3==1.40.70",
    "flask==3.1.1", # vuln
    "h11==0.16.0", # vuln
    "jinja2==3.1.6", # vuln
    "mlflow==3.5.1",
    "protobuf==5.29.5", # vuln
    "psycopg2-binary==2.9.11",
    "requests==2.32.4", # vuln
    "starlette>=0.49.1", # vuln
    "urllib3==2.5.0", # vuln
]

[tool.uv]
dev-dependencies = [
    "scikit-learn==1.7.2",
]
